spring.application.name=plantX
server.port=5000

wikipedia.mail=${WIKIPEDIA_EMAIL}
plantnet.api_key=${PLANTNET_API_KEY}
trefle.api_key=${TREFLECACHE_API_KEY}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.name=${CLOUDINARY_NAME}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB